name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show triggering event
        run: echo "Triggered by ${{ github.event_name }} event"
      
      - name: Determine trigger user;
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "Triggered by push event"
            echo "User: ${{ github.actor }}"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Triggered by pull request event"
            echo "User: ${{ github.actor }}"
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Triggered by workflow dispatch event"
            echo "User: ${{ github.actor }}"
          elif [ "${{ github.event_name }}" == "schedule" ]; then
            echo "Triggered by schedule event"
          else
            echo "Unknown trigger event"
          fi

      - uses: actions/checkout@v5

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 24
